### ISSUE TITLE
Please add websocket endpoints after created

### ISSUE THREAD

**Issue by Cerberus** [graphcool/graphql-up#12]
I have created [an example application](https://github.com/Cerberus/note) that use `graphql-up` as the endpoints and I've tried to execute subscription on playground. It work fine.
But I didn't not see the **Subscription API**. We need to manual put it like this..
`wss://subscriptions.graph.cool/v1/__path__`
Request for
```
  ✔  Your GraphQL API is ready to use. Here are your endpoints:

    ❯ Simple API: https://api.graph.cool/simple/v1/__path__
    ❯ Relay API:  https://api.graph.cool/relay/v1/__path__
    ❯ Subscription API:  wss://subscriptions.graph.cool/v1/__path__
```

**Comment by schickling** [comment]
Sounds good! Would you mind creating a PR?
