### ISSUE TITLE
Target an existing Graphcool Project

### ISSUE THREAD

**Issue by mewdriller** [graphcool/graphql-up#7]
It seems like the foundation of this tool could be leveraged to manage your Schema (and possibly your Permissions and Mutation Callbacks) via version-controlled files.

In the simplest case I'm imagining something like:

```
$ graphql-up login
$ graphql-up twitter.schema --project MyTwitter
```

This would probably require the addition of data-migration tooling as well to handle changes to the Schema that affect data integrity. Perhaps that could take on a similar API to Rails migrations with `rake db:migrate`?

**Comment by schickling** [comment]
Hi @mewdriller! Very good point, this will in fact be possible with the [Graphcool CLI](https://github.com/graphcool/feature-requests/issues/184) which will be released over the coming weeks.

Please [join our Slack](https://slack.graph.cool) to get access to the beta for the CLI. 🔜

**Comment by mewdriller** [comment]
Thanks for the quick response @schickling! I'll follow-up in the Slack channel RE the beta CLI.
